### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by achecopar** [scarrera/movie-manager#1]
Cuando trato de hacer mvn install me dice que tiene errores de compilación:

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. b
uild is platform dependent!
[INFO] Compiling 1 source file to E:\Obligatorio\movie-manager\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Obligatorio\movie-manager\src\main\java\services\MovieManagerImpl.java:
[148,44] error: incompatible types
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.969s
[INFO] Finished at: Sun Jun 09 12:36:25 UYT 2013
[INFO] Final Memory: 14M/34M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project movie-manager: Compilation failure
[ERROR] \Obligatorio\movie-manager\src\main\java\services\MovieManagerImpl.java:
[148,44] error: incompatible types
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

¿Pudieron hacer el build?

**Comment by scarrera** [comment]
Hola Ivana,

A mí me hace el build correctamente.
Intenta correr mvn clean install - e y se te da error pasame lo que te tira

**Comment by mg-um** [comment]
En efecto, el tipo de Movie.id is Long, no string:

https://github.com/marshhxx/modelstorage/blob/master/src/main/java/edu/umflix/model/Movie.java

Grupo B: deben actualizar el model storage y re hacer el build.

**Comment by scarrera** [comment]
Ok! Actualizado y corregido.
